[package]
name = "orion-app"
version = "0.7.0"
edition = "2024"
description = "Orion desktop client"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-opener = "2"
tauri-plugin-notification = "2"
tauri-plugin-autostart = "2"
orion-ipc = { path = "../../protocol" }
